//
// Created by Violator Emilie on 3/27/23.
//

#ifndef INC_3DVIEWER_V2_0_SRC_CONTROLLER_CONTROLLER_H_
#define INC_3DVIEWER_V2_0_SRC_CONTROLLER_CONTROLLER_H_

class controller {

};

#endif //INC_3DVIEWER_V2_0_SRC_CONTROLLER_CONTROLLER_H_
